// User action
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

// Article page
export const LOAD_ARTICLE_PAGE = 'LOAD_ARTICLE_PAGE';
export const RENDER_ARTICLE_PAGE = 'RENDER_ARTICLE_PAGE';

// Home page
export const LOAD_HOME_PAGE = 'LOAD_HOME_PAGE';
export const RENDER_HOME_PAGE = 'RENDER_HOME_PAGE';
export const LOAD_TAB = 'LOAD_TAB';
export const RENDER_TAB = 'RENDER_TAB';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const RENDER_ARTICLE = 'RENDER_ARTICLE';
export const LOAD_POPULAR_TAG = 'LOAD_POPULAR_TAG';
export const RENDER_POPULAR_TAG = 'RENDER_POPULAR_TAG';

export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CLICK_ON_TAB = 'CLICK_ON_TAB';
export const CHANGE_TAB = 'CHANGE_TAB';

export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const RENDER_CURRENT_USER = 'RENDER_CURRENT_USER';

export const LOAD_ARTICLE_COMMENT = 'LOAD_ARTICLE_COMMENT';
export const RENDER_ARTICLE_COMMENT = 'RENDER_ARTICLE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const APPEND_COMMENT = 'APPEND_COMMENT';

export const POST_COMMENT = 'POST_COMMENT';

// Book store
export const LOAD_LIST_BOOK = 'LOAD_LIST_BOOK';
export const RENDER_LIST_BOOK = 'RENDER_LIST_BOOK';

export const LOAD_BOOK_DETAIL = 'LOAD_BOOK_DETAIL';
export const RENDER_BOOK_DETAIL = 'RENDER_BOOK_DETAIL';

export const LOAD_ALL_AUTHOR = 'LOAD_ALL_AUTHOR';
export const RENDER_ALL_AUTHOR = 'RENDER_ALL_AUTHOR';

export const LOAD_ALL_CATEGORY = 'LOAD_ALL_CATEGORY';
export const RENDER_ALL_CATEGORY = 'RENDER_ALL_CATEGORY';

export const APPLY_FILTER_BOOK = 'APPLY_FILTER_BOOK';

export const LOAD_BOOK_HOME = 'LOAD_BOOK_HOME';
export const RENDER_BOOK_HOME = 'RENDER_BOOK_HOME';

export const LOAD_MORE_BOOK = 'LOAD_MORE_BOOK';
export const RENDER_MORE_BOOK = 'RENDER_MORE_BOOK';

export const CHANGE_ORDER = 'CHANGE_ORDER';